Mill/Models/ErrorViewModel.cs
namespace Mill.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mill/Models/Records.cs
using System;

namespace Mill.Models
{
    public class Records
    {
        public int Id { get; set; }
        public string? Order { get; set; }
        public string? Part { get; set; }
        public string? QTY { get; set; }
        public string? NAME { get; set; }
        public string? DATE { get; set; }
        public string? Run { get; set; }
        public string? MATERIAL { get; set; }
        public string? REASON { get; set; }
        public string? RoutingCode { get; set; }
        public string? COMMENT { get; set; }
        public string? WC { get; set; }
        public string? Optimized { get; set; }
        public string? OptimizedDate { get; set; }
        public string? Rush { get; set; }
        public string? CutAt  { get; set; }

}
}

Mill/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Mill.Models;
using System.Diagnostics;

namespace Mill.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
   
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mill/Controllers/LineController.cs
using AirtableApiClient;
using Microsoft.AspNetCore.Mvc;
using Mill.Models;
using Newtonsoft.Json;
using System.Data;
using System.Reflection.Emit;
using System.Xml.Linq;

namespace Mill.Controllers
{
    public class LineController : Controller
    {
        List<Records> recordsList = new List<Records>();
        List<AirtableRecord> reecords = new List<AirtableRecord>();
        DataTable dt = new DataTable();
        public IEnumerable<string> fields = new string[] { "Order #", "Part # +", "QTY", "NAME", "DATE", "Run Number (from Master List)", "MATERIAL/COLOUR", "REASON FOR REORDER", "Mill Routing Code", "COMMENT", "WC #", "Optimized", "Optimized Date", "Rush", "Cut @ Router Time" };
        public IEnumerable<string> headers= new string[] { "Order #", "Part #", "QTY", "NAME", "DATE", "Run", "MATERIAL/COLOUR", "REASON FOR REORD", "Mill", "COMMENT", "WC #", "Optimized", "Optimized Date", "Rush", "Cut @ Router" };

        private readonly IConfiguration _configuration;

        public LineController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Line1()
        {
            ViewBag.Columns = headers;
            return View();
        }

        public async Task<JsonResult> GetDataLine1()
        {
            string appKey = _configuration.GetSection("AirtableApiLogin").GetValue<string>("APPKEY");
            string baseId = _configuration.GetSection("AirtableApiLogin").GetValue<string>("BASEID");
            string table = _configuration.GetSection("AirtableApiLogin").GetValue<string>("TABLE");
            string tableview = "Master List";
            string offset = null;
            string errorMessage = null;
            string timeZone = "America/North_Dakota/Center";
            string cellFormat = "string";
            string userLocale = "en-ca";
            string filterByFormulaLine1 = "FIND('1', {Mill Routing Code}) > 0";

            try
            {
                using (AirtableBase airtableBase = new AirtableBase(appKey, baseId))
                {
                    do
                    {
                        Task<AirtableListRecordsResponse> task = airtableBase.ListRecords(
                        table,
                               offset,
                               fields,
                               filterByFormulaLine1,
                               null,
                               null,
                               null,
                               tableview,
                               cellFormat,
                               timeZone,
                               userLocale,
                               false
                           );

                        AirtableListRecordsResponse response = await task;
                        if (response.Success)
                        {
                            reecords.AddRange(response.Records.ToList());
                            offset = response.Offset;
                        }
                        else if (response.AirtableApiError is AirtableApiException)
                        {
                            errorMessage = response.AirtableApiError.ErrorMessage;
                            if (response.AirtableApiError is AirtableInvalidRequestException)
                            {
                                errorMessage += "\nDetailed error message: ";
                                errorMessage += response.AirtableApiError.DetailedErrorMessage;
                                ViewBag.Error = errorMessage;
                            }
                            break;
                        }
                        else
                        {
                            ViewBag.Error = "Unknown error";
                            break;
                        }
                    } while (offset != null);
                }

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            if (!string.IsNullOrEmpty(errorMessage))
            {
                ViewBag.Error = errorMessage;
            }

            else
            {
                foreach (string field in fields)
                {
                    dt.Columns.Add(field);
                }

                int i = 0;
                reecords.Reverse();
                foreach (var record in reecords)
                {

                    DataRow dr = dt.NewRow();
                    
                    foreach (var columns in record.Fields)
                    {
                        dr[columns.Key.ToString()] = columns.Value.ToString();
                    }
                        recordsList.Add(new Records {
                            Id = i++,
                            Order = dr["Order #"].ToString(),
                            Part = dr["Part # +"].ToString(),
                            NAME = dr["NAME"].ToString(),
                            QTY = dr["QTY"].ToString(),
                            DATE = dr["DATE"].ToString(),
                            Run = dr["Run Number (from Master List)"].ToString(),
                            MATERIAL = dr["MATERIAL/COLOUR"].ToString(),
                            REASON = dr["REASON FOR REORDER"].ToString(),
                            RoutingCode = dr["Mill Routing Code"].ToString(),
                            COMMENT = dr["COMMENT"].ToString(),
                            WC = dr["WC #"].ToString(),
                            Optimized = dr["Optimized"].ToString(),
                            OptimizedDate = dr["Optimized Date"].ToString(),
                            Rush = dr["Rush"].ToString(),
                            CutAt = dr["Cut @ Router Time"].ToString(),
                        });;
                }
            }
            return Json(recordsList);
        }
    }
}

Mill/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Mill/Views/Line/Line1.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.css">

    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.4/dist/extensions/cookie/bootstrap-table-cookie.min.js"></script>
</head>

<body>
    <table id="table"
        data-search="true"
        data-show-refresh="true" 
        data-show-fullscreen="true" 
        data-row-style="rowStyle"
        data-show-columns="true"
        data-cookie="true"
        data-buttons="buttons"
        data-cookie-id-table="saveId">
        <thead>
            <tr>
                <th data-sortable="true">id</th>
                @foreach (string column in ViewBag.Columns)
                {
                    <th>@column</th>
                }
            </tr>   
        </thead>
    </table>

    <script>
        var recordData = [];
        var $table = $('#table')
        $.ajax({
            type: "POST",
            url: "/Line/GetDataLine1/",
            async: false,
            success: function (data) {
                $.each(data, function (key, value) {
                    recordData.push([value.id, value.order, value.part, value.qty, value.name, value.date, value.run, value.material, value.reason, value.routingCode, value.comment, value.wc, value.optimized, value.optimizedDate, value.rush, value.cutAt])
                }),
                    $table.bootstrapTable({ data: recordData })
                    
            },
            failure: function (err) { }
        });


        function rowStyle(row, index) {
            if (row[14] === '**RUSH**') {
                return {
                    classes: 'bg-redd'
                }
            }
            if (row[15] != 0) {
                return {
                    classes: 'bg-gree'
                }
            }
            return {
                css: {
                    color: 'black'
                }
            }
        }

        $table.bootstrapTable('toggleFullscreen')

        function buttons() {
            return {
                btnUsersAdd: {
                    text: 'Hide complited',
                    icon: 'bi-bag-dash',
                            event: function () {
                        var dataTable = $table.bootstrapTable('getData');
                        dataTable.forEach(function (key, value) {
                           
                            if(key[15] != 0) {$table.bootstrapTable('hideRow', {index: value})}

                            console.log('value-' + value + 'Hidden-')
                             }
                        )},

                    attributes: {
                        title: 'Hide finished orders'
                    }
                },
                btnAdd: {
                    text: 'Show all',
                    icon: 'bi-bag-check-fill',
                    event: function () {
                        $table.bootstrapTable('getHiddenRows', true)
                    },

                    attributes: {
                        title: 'Add a new row to the table'
                    }
                }
            }   
        }

    </script>
</body>
</html>

Mill/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mill</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mill.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mill</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Line" asp-action="Line1">Line 1</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>